---
title: Packet Writer
---

stateDiagram-v2
  [*] --> PacketHeaders: write_headers
  PacketHeaders --> Tlv: write_tlv
  Tlv --> FinishedTlv: finish_tlv
  FinishedTlv --> Tlv: write_tlv
  Tlv --> Tlv: write_sub_tlv
  FinishedTlv --> FinishedPacketBody: finish_body
  


