---
title: Packet Writer
---

stateDiagram-v2
  [*] --> Ready: write_headers
  Ready --> Tlv: write_tlv
  Tlv --> Ready: finish_tlv
  Tlv --> Tlv: write_sub_tlv
  Ready --> FinishedPacketBody: finish_body
  


